// generated by "sampctl package generate"

#include "MV_Youtube.inc"

new test, myPlaylist, another;

main() {
	// write tests for libraries here and run "sampctl package run"
	test = PlayYoutubeVideoFor("https://www.youtube.com/watch?v=TyHvyGVs42U");
	SetTimer("OnTestVideo", 10000, false);

	myPlaylist = CreatePlaylist("Testing");
	another = PlayYoutubeVideoFor("https://www.youtube.com/watch?v=uGhKqb2Ow3E", INVALID_PLAYER_ID, myPlaylist);
	SetTimer("OnTestPlaylist", 10000, false);
}

forward OnTestVideo();
public OnTestVideo()
{
	printf("%s", GetVideoTitle(test));
	printf("%s", GetVideoLink(test));
	printf("%i", GetVideoDuration(test));
	printf("%s", GetVideoStreamLink(test));
	printf("%i", GetVideoTarget(test));
}

forward OnTestPlaylist();
public OnTestPlaylist()
{
	printf("%s", GetPlaylistName(myPlaylist));
	printf("%i", GetPlaylistSongsCount(myPlaylist));
	printf("%i", GetPlaylistFromVideo(another));
}
