// generated by "sampctl package generate"

#include "MV_Youtube.inc"

new youtube_ids[3], myPlaylist;

main() {
	for (new i = 0; i < sizeof(youtube_ids); i++) 
		youtube_ids[i] = INVALID_YT_ID;

	youtube_ids[0] = PlayYoutubeVideoFor("https://www.youtube.com/watch?v=TyHvyGVs42U");
	SetTimer("OnTest", 10000, false);

	SearchYoutubeVideos(0, "michaelbelgium");
}

forward OnTest();
public OnTest()
{
	printSong(0);

	myPlaylist = CreatePlaylist("Playlist 1");
	youtube_ids[1] = PlayYoutubeVideoFor("https://www.youtube.com/watch?v=uGhKqb2Ow3E", INVALID_PLAYER_ID, myPlaylist);
	youtube_ids[2] = PlayYoutubeVideoFor("https://www.youtube.com/watch?v=NkrkAsRVLEA", INVALID_PLAYER_ID, myPlaylist);
	SetTimer("OnTestPlaylist", 10000, false);
}

forward OnTestPlaylist();
public OnTestPlaylist()
{
	printSong(1);
	printSong(2);

	print("---------- Testing playlist response ----------");
	printf("Id: %i", myPlaylist);
	printf("Name: %s", GetPlaylistName(myPlaylist));
	printf("Songcount: %i", GetPlaylistSongsCount(myPlaylist));
}

stock printSong(index)
{
	printf("---------- Testing video response %i ----------", youtube_ids[index]);
	printf("Title: %s", GetVideoTitle(youtube_ids[index]));
	printf("Link: %s", GetVideoLink(youtube_ids[index]));
	printf("Duration: %i seconds", GetVideoDuration(youtube_ids[index]));
	printf("Stream: %s", GetVideoStreamLink(youtube_ids[index]));
	printf("Play for: %i", GetVideoTarget(youtube_ids[index]));
	printf("Playlist id: %i", GetPlaylistFromVideo(youtube_ids[index]));
}

public OnMVYoutubeError(youtubeid, const message[])
{
	printf("Video %i encountered an error: %s", youtubeid, message);
}

public OnPlaylistAddEntry(playerlistid, youtubeid)
{
	printf("Added video %i to playlist %i", youtubeid, playerlistid);
}

public OnYoutubeVideoStart(youtubeid)
{
	printf("Video %i started", youtubeid);
}

public OnPlaylistFinished(playlistid)
{
	printf("Playlist %i finished", playlistid);
}

public OnYoutubeSearch(playerid)
{
	print("---------- Search response ----------");

	for(new i = 0; i < MAX_SEARCH_RESULTS; i++)
	{
		printf("Title: %s", SearchResults[playerid][i][Title]);
		printf("Link: %s", SearchResults[playerid][i][Link]);
	}
}